### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by myl82** [microsoft/K8s-Storage-Plugins#21]
Try to mount share into windows pod. GKE cluster with windows node v1.16.9-gke.6 (windows server DC 2019ltsc 10.0.17763.1098)
kubelet.exe  ... --volume-plugin-dir=C:\etc\kubernetes\flexvolume .....
I've unpacked archive with plugin, apply smb-secret.yml and smb.yml, but still getting mistake:
      __`Warning  FailedMount  kubelet, gke-win-test-v2-windows-6be2eef6-jckk  Unable to attach or mount volumes: unmounted volumes=[smb-volume], unattached volumes=[default-token-gpblr smb-volume]: failed to get Plugin from volumeSpec for volume "smb-volume" err=no volume plugin matched`__

What's wrong?

**Comment by servo1x** [comment]
@myl82 what was the resolution for this?
